import type {
  Course,
  GradeLevel,
  Level,
  PrereqGroup,
  SchoolConfig,
  Season,
  SourceRef,
  Workload,
} from '../engine/types.ts'

/**
 * Compass Demo High School -- DEVELOPMENT DATA.
 *
 * A fictional catalog used until a real school's catalog (for example
 * coursed.pdf) has been extracted and reviewed. It does not describe any real
 * school's courses or graduation requirements. Every record carries a `seed`
 * source so the UI and Compass AI say so instead of presenting it as policy.
 */

const SEED: SourceRef = { kind: 'seed', document: 'Compass demo catalog (development data)' }
const MODEL: SourceRef = { kind: 'school-config', document: 'Compass default school model' }

const ALL: GradeLevel[] = [9, 10, 11, 12]
const g = (...grades: GradeLevel[]) => grades

const before = (...ids: string[]): PrereqGroup => ({ anyOf: ids.map((courseId) => ({ courseId, timing: 'before' })) })
const beforeOrWith = (...ids: string[]): PrereqGroup => ({
  anyOf: ids.map((courseId) => ({ courseId, timing: 'before-or-concurrent' })),
})

interface Spec {
  id: string
  name: string
  department: string
  description: string
  level?: Level
  length: 'year' | 'semester'
  seasons?: Season[]
  grades: GradeLevel[]
  prerequisites?: PrereqGroup[]
  workload?: Workload
  lab?: boolean
  tags: string[]
  satisfies?: string[]
  sequence?: { id: string; step: number }
  equivalenceGroup?: string
  maxEnrollments?: number
  expectsBackground?: boolean
  notes?: string[]
}

function course(spec: Spec): Course {
  const year = spec.length === 'year'
  return {
    id: spec.id,
    name: spec.name,
    department: spec.department,
    description: spec.description,
    credits: year ? 1 : 0.5,
    durationTerms: year ? 2 : 1,
    grades: spec.grades,
    seasons: year ? ['fall'] : (spec.seasons ?? ['fall', 'spring']),
    prerequisites: spec.prerequisites ?? [],
    level: spec.level ?? 'standard',
    workload: spec.workload ?? 2,
    ...(spec.lab ? { lab: true } : {}),
    tags: spec.tags,
    satisfies: spec.satisfies ?? [],
    ...(spec.sequence ? { sequence: spec.sequence } : {}),
    ...(spec.equivalenceGroup ? { equivalenceGroup: spec.equivalenceGroup } : {}),
    ...(spec.maxEnrollments ? { maxEnrollments: spec.maxEnrollments } : {}),
    ...(spec.expectsBackground ? { expectsBackground: true } : {}),
    ...(spec.notes ? { notes: spec.notes } : {}),
    source: SEED,
  }
}

const english = (s: Omit<Spec, 'department' | 'satisfies'>) =>
  course({ ...s, department: 'english', satisfies: ['english'] })
const math = (s: Omit<Spec, 'department' | 'satisfies'>) => course({ ...s, department: 'math', satisfies: ['math'] })
const science = (s: Omit<Spec, 'department' | 'satisfies'>) =>
  course({ ...s, department: 'science', satisfies: ['science'] })
const social = (s: Omit<Spec, 'department' | 'satisfies'>) =>
  course({ ...s, department: 'social-studies', satisfies: ['social-studies'] })
const language = (s: Omit<Spec, 'department' | 'satisfies'>) =>
  course({ ...s, department: 'world-language', satisfies: ['world-language'] })
const arts = (s: Omit<Spec, 'department' | 'satisfies'>) =>
  course({ ...s, department: 'fine-arts', satisfies: ['fine-arts'] })

const ALGEBRA_1 = ['algebra-1']
const GEOMETRY = ['geometry', 'honors-geometry']
const ALGEBRA_2 = ['algebra-2', 'honors-algebra-2']
const BIOLOGY = ['biology', 'honors-biology']
const CHEMISTRY = ['chemistry', 'honors-chemistry']
const ENGLISH_10 = ['english-10', 'honors-english-10']
const ENGLISH_11 = ['english-11', 'ap-english-language']

const courses: Course[] = [
  // English
  english({
    id: 'english-9',
    name: 'English 9',
    description: 'Reading, writing, and discussion built around short fiction, poetry, a Shakespeare play, and the personal essay.',
    length: 'year',
    grades: g(9),
    tags: ['writing', 'literature', 'humanities'],
    equivalenceGroup: 'english-9',
  }),
  english({
    id: 'honors-english-9',
    name: 'Honors English 9',
    description: 'English 9 at a faster pace, with more independent reading and longer analytical essays.',
    level: 'honors',
    length: 'year',
    grades: g(9),
    workload: 3,
    tags: ['writing', 'literature', 'humanities'],
    equivalenceGroup: 'english-9',
  }),
  english({
    id: 'english-10',
    name: 'English 10',
    description: 'World literature and argument writing: how authors build a case, and how to build your own.',
    length: 'year',
    grades: g(10),
    prerequisites: [before('english-9', 'honors-english-9')],
    tags: ['writing', 'literature', 'humanities'],
    equivalenceGroup: 'english-10',
  }),
  english({
    id: 'honors-english-10',
    name: 'Honors English 10',
    description: 'English 10 with added research writing and seminar-style discussion.',
    level: 'honors',
    length: 'year',
    grades: g(10),
    prerequisites: [before('english-9', 'honors-english-9')],
    workload: 3,
    tags: ['writing', 'literature', 'humanities'],
    equivalenceGroup: 'english-10',
  }),
  english({
    id: 'english-11',
    name: 'English 11: American Literature',
    description: 'American voices from the colonial era to today, with a focus on analytical and narrative writing.',
    length: 'year',
    grades: g(11),
    prerequisites: [before(...ENGLISH_10)],
    tags: ['writing', 'literature', 'humanities'],
    equivalenceGroup: 'english-11',
  }),
  english({
    id: 'ap-english-language',
    name: 'AP English Language and Composition',
    description: 'Rhetoric and argument: analyzing how writers persuade, and writing timed and researched arguments.',
    level: 'ap',
    length: 'year',
    grades: g(11),
    prerequisites: [before(...ENGLISH_10)],
    workload: 3,
    tags: ['writing', 'humanities'],
    equivalenceGroup: 'english-11',
  }),
  english({
    id: 'english-12',
    name: 'English 12: World Literature',
    description: 'Novels, drama, and poetry from around the world, and a senior research paper.',
    length: 'year',
    grades: g(12),
    prerequisites: [before(...ENGLISH_11)],
    tags: ['writing', 'literature', 'humanities'],
    equivalenceGroup: 'english-12',
  }),
  english({
    id: 'ap-english-literature',
    name: 'AP English Literature and Composition',
    description: 'Close reading of fiction, poetry, and drama, with frequent literary-analysis essays.',
    level: 'ap',
    length: 'year',
    grades: g(12),
    prerequisites: [before(...ENGLISH_11)],
    workload: 3,
    tags: ['writing', 'literature', 'humanities'],
    equivalenceGroup: 'english-12',
  }),
  course({
    id: 'creative-writing',
    name: 'Creative Writing',
    department: 'english',
    description: 'Workshop-based fiction and poetry writing, with peer critique and a final portfolio.',
    length: 'semester',
    grades: g(10, 11, 12),
    tags: ['writing', 'arts', 'humanities'],
  }),
  course({
    id: 'journalism',
    name: 'Journalism',
    department: 'english',
    description: 'Reporting, interviewing, and editing for the school news site.',
    length: 'year',
    grades: g(10, 11, 12),
    tags: ['writing', 'media', 'humanities'],
  }),
  course({
    id: 'speech-and-debate',
    name: 'Speech and Debate',
    department: 'english',
    description: 'Public speaking, research, and competitive debate formats.',
    length: 'year',
    grades: ALL,
    tags: ['humanities', 'public-speaking', 'leadership'],
  }),
  course({
    id: 'film-studies',
    name: 'Film Studies',
    department: 'english',
    description: 'How films tell stories: shots, editing, sound, and genre, with short analytical writing.',
    length: 'semester',
    grades: g(11, 12),
    workload: 1,
    tags: ['humanities', 'media', 'arts'],
  }),

  // Mathematics
  math({
    id: 'algebra-1',
    name: 'Algebra 1',
    description: 'Linear equations and inequalities, functions, systems, exponents, and an introduction to quadratics.',
    length: 'year',
    grades: g(9, 10),
    tags: ['math'],
    equivalenceGroup: 'algebra-1',
  }),
  math({
    id: 'geometry',
    name: 'Geometry',
    description: 'Proof, congruence and similarity, right-triangle trigonometry, circles, area, and volume.',
    length: 'year',
    grades: g(9, 10, 11),
    prerequisites: [before(...ALGEBRA_1)],
    tags: ['math'],
    equivalenceGroup: 'geometry',
  }),
  math({
    id: 'honors-geometry',
    name: 'Honors Geometry',
    description: 'Geometry with more formal proof and harder problem solving.',
    level: 'honors',
    length: 'year',
    grades: g(9, 10),
    prerequisites: [before(...ALGEBRA_1)],
    workload: 3,
    tags: ['math'],
    equivalenceGroup: 'geometry',
  }),
  math({
    id: 'algebra-2',
    name: 'Algebra 2',
    description: 'Polynomial, rational, exponential, and logarithmic functions, and an introduction to trigonometric functions.',
    length: 'year',
    grades: ALL,
    prerequisites: [before(...GEOMETRY)],
    tags: ['math'],
    equivalenceGroup: 'algebra-2',
  }),
  math({
    id: 'honors-algebra-2',
    name: 'Honors Algebra 2',
    description: 'Algebra 2 with added depth in functions, sequences, and complex numbers.',
    level: 'honors',
    length: 'year',
    grades: g(9, 10, 11),
    prerequisites: [before(...GEOMETRY)],
    workload: 3,
    tags: ['math'],
    equivalenceGroup: 'algebra-2',
  }),
  math({
    id: 'precalculus',
    name: 'Precalculus',
    description: 'Functions, trigonometry, vectors, and limits: the bridge from algebra to calculus.',
    length: 'year',
    grades: g(10, 11, 12),
    prerequisites: [before(...ALGEBRA_2)],
    tags: ['math'],
    equivalenceGroup: 'precalculus',
  }),
  math({
    id: 'ap-precalculus',
    name: 'AP Precalculus',
    description: 'College-level precalculus: polynomial, rational, exponential, logarithmic, trigonometric, and polar functions.',
    level: 'ap',
    length: 'year',
    grades: ALL,
    prerequisites: [before(...ALGEBRA_2)],
    workload: 3,
    tags: ['math'],
    equivalenceGroup: 'precalculus',
  }),
  math({
    id: 'ap-calculus-ab',
    name: 'AP Calculus AB',
    description: 'Limits, derivatives, and integrals, with applications. Equivalent to a first semester of college calculus.',
    level: 'ap',
    length: 'year',
    grades: g(10, 11, 12),
    prerequisites: [before('precalculus', 'ap-precalculus')],
    workload: 3,
    tags: ['math', 'engineering'],
    equivalenceGroup: 'calculus',
  }),
  math({
    id: 'ap-calculus-bc',
    name: 'AP Calculus BC',
    description: 'Everything in Calculus AB plus series, parametric and polar calculus. Equivalent to two semesters of college calculus.',
    level: 'ap',
    length: 'year',
    grades: g(10, 11, 12),
    prerequisites: [before('ap-precalculus')],
    workload: 4,
    tags: ['math', 'engineering', 'physics'],
    equivalenceGroup: 'calculus',
  }),
  math({
    id: 'ap-statistics',
    name: 'AP Statistics',
    description: 'Collecting, describing, and drawing conclusions from data, with probability and inference.',
    level: 'ap',
    length: 'year',
    grades: g(10, 11, 12),
    prerequisites: [before(...ALGEBRA_2)],
    workload: 3,
    tags: ['math', 'data', 'business', 'medicine'],
    equivalenceGroup: 'statistics',
  }),
  math({
    id: 'statistics',
    name: 'Statistics and Data Science',
    description: 'Hands-on statistics with real data sets, spreadsheets, and simple visualizations.',
    length: 'year',
    grades: g(11, 12),
    prerequisites: [before(...ALGEBRA_2)],
    tags: ['math', 'data', 'business'],
    equivalenceGroup: 'statistics',
  }),
  math({
    id: 'financial-algebra',
    name: 'Financial Algebra',
    description: 'Algebra applied to budgeting, credit, taxes, loans, and investing.',
    length: 'year',
    grades: g(11, 12),
    prerequisites: [before(...GEOMETRY)],
    tags: ['math', 'finance', 'business'],
  }),
  math({
    id: 'multivariable-calculus',
    name: 'Multivariable Calculus',
    description: 'Calculus in three dimensions: partial derivatives, multiple integrals, and vector fields.',
    level: 'post-ap',
    length: 'semester',
    seasons: ['fall'],
    grades: g(11, 12),
    prerequisites: [before('ap-calculus-bc')],
    workload: 4,
    tags: ['math', 'engineering', 'physics'],
  }),
  math({
    id: 'linear-algebra',
    name: 'Linear Algebra',
    description: 'Vectors, matrices, linear transformations, and eigenvalues: the math behind graphics, data science, and engineering.',
    level: 'post-ap',
    length: 'semester',
    seasons: ['spring'],
    grades: g(11, 12),
    prerequisites: [before('ap-calculus-bc')],
    workload: 4,
    tags: ['math', 'computer-science', 'engineering'],
  }),
  math({
    id: 'differential-equations',
    name: 'Differential Equations',
    description: 'Modeling change with first- and second-order differential equations.',
    level: 'post-ap',
    length: 'semester',
    seasons: ['spring'],
    grades: g(12),
    prerequisites: [before('multivariable-calculus')],
    workload: 4,
    tags: ['math', 'engineering', 'physics'],
  }),
  math({
    id: 'discrete-mathematics',
    name: 'Discrete Mathematics',
    description: 'Logic, counting, graphs, and proof: the math of computer science.',
    level: 'honors',
    length: 'semester',
    seasons: ['fall'],
    grades: g(11, 12),
    prerequisites: [before('precalculus', 'ap-precalculus')],
    workload: 3,
    tags: ['math', 'computer-science'],
  }),

  // Science
  science({
    id: 'biology',
    name: 'Biology',
    description: 'Cells, genetics, evolution, and ecosystems, with weekly labs.',
    length: 'year',
    grades: g(9, 10),
    lab: true,
    tags: ['science', 'biology', 'medicine'],
    equivalenceGroup: 'biology',
  }),
  science({
    id: 'honors-biology',
    name: 'Honors Biology',
    description: 'Biology with more independent lab design and deeper molecular and cellular content.',
    level: 'honors',
    length: 'year',
    grades: g(9, 10),
    workload: 3,
    lab: true,
    tags: ['science', 'biology', 'medicine'],
    equivalenceGroup: 'biology',
  }),
  science({
    id: 'chemistry',
    name: 'Chemistry',
    description: 'Atoms, bonding, reactions, stoichiometry, and gases, with weekly labs.',
    length: 'year',
    grades: g(10, 11, 12),
    prerequisites: [before(...BIOLOGY), before(...ALGEBRA_1)],
    workload: 3,
    lab: true,
    tags: ['science', 'chemistry', 'medicine'],
    equivalenceGroup: 'chemistry',
  }),
  science({
    id: 'honors-chemistry',
    name: 'Honors Chemistry',
    description: 'Chemistry with more quantitative problem solving and formal lab reports.',
    level: 'honors',
    length: 'year',
    grades: g(10, 11, 12),
    prerequisites: [before(...BIOLOGY), beforeOrWith(...GEOMETRY)],
    workload: 3,
    lab: true,
    tags: ['science', 'chemistry', 'medicine'],
    equivalenceGroup: 'chemistry',
  }),
  science({
    id: 'physics',
    name: 'Physics',
    description: 'Motion, forces, energy, waves, and electricity, taught through experiments.',
    length: 'year',
    grades: g(11, 12),
    prerequisites: [before(...GEOMETRY)],
    lab: true,
    tags: ['science', 'physics', 'engineering'],
    equivalenceGroup: 'physics-1',
  }),
  science({
    id: 'ap-physics-1',
    name: 'AP Physics 1',
    description: 'Algebra-based college physics: mechanics, energy, momentum, rotation, and waves.',
    level: 'ap',
    length: 'year',
    grades: g(10, 11, 12),
    prerequisites: [before(...GEOMETRY), beforeOrWith(...ALGEBRA_2)],
    workload: 4,
    lab: true,
    tags: ['science', 'physics', 'engineering'],
    equivalenceGroup: 'physics-1',
  }),
  science({
    id: 'ap-physics-2',
    name: 'AP Physics 2',
    description: 'Algebra-based college physics continued: fluids, thermodynamics, electricity, magnetism, optics, and modern physics.',
    level: 'ap',
    length: 'year',
    grades: g(11, 12),
    prerequisites: [before('ap-physics-1')],
    workload: 4,
    lab: true,
    tags: ['science', 'physics', 'engineering'],
  }),
  science({
    id: 'ap-physics-c-mechanics',
    name: 'AP Physics C: Mechanics',
    description: 'Calculus-based mechanics, equivalent to a first college physics course for engineers.',
    level: 'ap',
    length: 'year',
    grades: g(11, 12),
    prerequisites: [before('physics', 'ap-physics-1'), beforeOrWith('ap-calculus-ab', 'ap-calculus-bc')],
    workload: 4,
    lab: true,
    tags: ['science', 'physics', 'engineering', 'math'],
  }),
  science({
    id: 'ap-chemistry',
    name: 'AP Chemistry',
    description: 'College general chemistry: equilibrium, kinetics, thermodynamics, and electrochemistry, with extended labs.',
    level: 'ap',
    length: 'year',
    grades: g(11, 12),
    prerequisites: [before(...CHEMISTRY), before(...ALGEBRA_2)],
    workload: 4,
    lab: true,
    tags: ['science', 'chemistry', 'medicine', 'engineering'],
  }),
  science({
    id: 'ap-biology',
    name: 'AP Biology',
    description: 'College introductory biology: biochemistry, cell processes, genetics, evolution, and ecology.',
    level: 'ap',
    length: 'year',
    grades: g(11, 12),
    prerequisites: [before(...BIOLOGY), before(...CHEMISTRY)],
    workload: 4,
    lab: true,
    tags: ['science', 'biology', 'medicine'],
  }),
  science({
    id: 'ap-environmental-science',
    name: 'AP Environmental Science',
    description: 'Earth systems, ecology, energy, pollution, and sustainability, with field and lab work.',
    level: 'ap',
    length: 'year',
    grades: g(10, 11, 12),
    prerequisites: [before(...BIOLOGY)],
    workload: 3,
    lab: true,
    tags: ['science', 'environment', 'biology'],
  }),
  science({
    id: 'anatomy-physiology',
    name: 'Anatomy and Physiology',
    description: 'The structure and function of the human body, system by system, with dissection labs.',
    level: 'honors',
    length: 'year',
    grades: g(11, 12),
    prerequisites: [before(...BIOLOGY), before(...CHEMISTRY)],
    workload: 3,
    lab: true,
    tags: ['science', 'biology', 'medicine', 'health-science'],
  }),
  science({
    id: 'earth-space-science',
    name: 'Earth and Space Science',
    description: 'Geology, weather and climate, oceans, and astronomy.',
    length: 'year',
    grades: ALL,
    lab: true,
    tags: ['science', 'environment'],
  }),
  science({
    id: 'forensic-science',
    name: 'Forensic Science',
    description: 'Crime-scene science: evidence collection, fingerprinting, blood-spatter analysis, and toxicology.',
    length: 'semester',
    grades: g(11, 12),
    prerequisites: [before(...BIOLOGY), before(...CHEMISTRY)],
    lab: true,
    tags: ['science', 'chemistry', 'biology'],
  }),

  // Social studies
  social({
    id: 'world-history',
    name: 'World History',
    description: 'Global history from early civilizations to the present, with document analysis and writing.',
    length: 'year',
    grades: g(9, 10),
    tags: ['history', 'humanities'],
    equivalenceGroup: 'world-history',
  }),
  social({
    id: 'honors-world-history',
    name: 'Honors World History',
    description: 'World History with more primary sources and a research project.',
    level: 'honors',
    length: 'year',
    grades: g(9, 10),
    workload: 3,
    tags: ['history', 'humanities'],
    equivalenceGroup: 'world-history',
  }),
  social({
    id: 'ap-world-history',
    name: 'AP World History: Modern',
    description: 'College-level world history from 1200 CE to the present.',
    level: 'ap',
    length: 'year',
    grades: g(10, 11, 12),
    workload: 4,
    tags: ['history', 'humanities'],
    equivalenceGroup: 'world-history',
  }),
  social({
    id: 'us-history',
    name: 'U.S. History',
    description: 'The United States from its founding to the present.',
    length: 'year',
    grades: g(11),
    tags: ['history', 'humanities'],
    equivalenceGroup: 'us-history',
  }),
  social({
    id: 'ap-us-history',
    name: 'AP U.S. History',
    description: 'College-level U.S. history with heavy reading and document-based essays.',
    level: 'ap',
    length: 'year',
    grades: g(11, 12),
    workload: 4,
    tags: ['history', 'humanities'],
    equivalenceGroup: 'us-history',
  }),
  social({
    id: 'us-government',
    name: 'U.S. Government',
    description: 'How American government works: the Constitution, the three branches, elections, and civic participation.',
    length: 'semester',
    grades: g(12),
    tags: ['history', 'humanities', 'civics'],
    equivalenceGroup: 'government',
  }),
  social({
    id: 'ap-us-government',
    name: 'AP U.S. Government and Politics',
    description: 'College-level study of American political institutions, required Supreme Court cases, and founding documents.',
    level: 'ap',
    length: 'semester',
    seasons: ['fall'],
    grades: g(12),
    workload: 3,
    tags: ['history', 'humanities', 'civics'],
    equivalenceGroup: 'government',
  }),
  social({
    id: 'economics',
    name: 'Economics',
    description: 'Supply and demand, markets, money, and personal economic decisions.',
    length: 'semester',
    grades: g(12),
    tags: ['economics', 'business'],
    equivalenceGroup: 'macroeconomics',
  }),
  social({
    id: 'ap-macroeconomics',
    name: 'AP Macroeconomics',
    description: 'College-level macroeconomics: national income, inflation, unemployment, and monetary and fiscal policy.',
    level: 'ap',
    length: 'semester',
    seasons: ['spring'],
    grades: g(11, 12),
    workload: 3,
    tags: ['economics', 'business'],
    equivalenceGroup: 'macroeconomics',
  }),
  social({
    id: 'ap-microeconomics',
    name: 'AP Microeconomics',
    description: 'College-level microeconomics: how individuals and firms make decisions, and how markets work.',
    level: 'ap',
    length: 'semester',
    seasons: ['fall'],
    grades: g(11, 12),
    workload: 3,
    tags: ['economics', 'business'],
  }),
  social({
    id: 'ap-human-geography',
    name: 'AP Human Geography',
    description: 'Population, culture, political organization, cities, and land use around the world.',
    level: 'ap',
    length: 'year',
    grades: ALL,
    workload: 3,
    tags: ['history', 'humanities', 'geography'],
  }),
  social({
    id: 'ap-european-history',
    name: 'AP European History',
    description: 'College-level European history from 1450 to the present.',
    level: 'ap',
    length: 'year',
    grades: g(10, 11, 12),
    workload: 4,
    tags: ['history', 'humanities'],
  }),
  social({
    id: 'ap-psychology',
    name: 'AP Psychology',
    description: 'College introductory psychology: the brain, learning, memory, development, and mental health.',
    level: 'ap',
    length: 'year',
    grades: g(10, 11, 12),
    workload: 3,
    tags: ['psychology', 'humanities', 'medicine'],
    equivalenceGroup: 'psychology',
  }),
  social({
    id: 'psychology',
    name: 'Psychology',
    description: 'An introduction to how people think, feel, and behave.',
    length: 'semester',
    grades: g(10, 11, 12),
    tags: ['psychology', 'humanities'],
    equivalenceGroup: 'psychology',
  }),
  social({
    id: 'sociology',
    name: 'Sociology',
    description: 'How groups, institutions, and culture shape people’s lives.',
    length: 'semester',
    grades: g(10, 11, 12),
    tags: ['humanities', 'sociology'],
  }),
  social({
    id: 'philosophy',
    name: 'Philosophy',
    description: 'Big questions in ethics, knowledge, and mind, argued in discussion and short essays.',
    level: 'honors',
    length: 'semester',
    grades: g(11, 12),
    workload: 3,
    tags: ['philosophy', 'humanities', 'writing'],
  }),

  // World language
  ...(['spanish', 'french', 'chinese'] as const).flatMap((lang): Course[] => {
    const label = { spanish: 'Spanish', french: 'French', chinese: 'Mandarin Chinese' }[lang]
    const culture = { spanish: 'Spanish-speaking', french: 'French-speaking', chinese: 'Chinese-speaking' }[lang]
    const tags = ['language', 'humanities']
    const list: Course[] = [
      language({
        id: `${lang}-1`,
        name: `${label} 1`,
        description: `Everyday conversation, core grammar, and an introduction to ${culture} cultures.`,
        length: 'year',
        grades: ALL,
        tags,
        sequence: { id: lang, step: 1 },
      }),
      language({
        id: `${lang}-2`,
        name: `${label} 2`,
        description: `Past and future tenses, longer conversations, and short readings.`,
        length: 'year',
        grades: ALL,
        prerequisites: [before(`${lang}-1`)],
        tags,
        sequence: { id: lang, step: 2 },
      }),
      language({
        id: `${lang}-3`,
        name: `${label} 3`,
        description: `Complex grammar, authentic texts, and extended speaking and writing.`,
        length: 'year',
        grades: ALL,
        prerequisites: [before(`${lang}-2`)],
        workload: 3,
        tags,
        sequence: { id: lang, step: 3 },
      }),
      language({
        id: `honors-${lang}-4`,
        name: `Honors ${label} 4`,
        description: `Advanced communication through literature, film, and current events, taught in the language.`,
        level: 'honors',
        length: 'year',
        grades: g(10, 11, 12),
        prerequisites: [before(`${lang}-3`)],
        workload: 3,
        tags,
        sequence: { id: lang, step: 4 },
      }),
    ]
    if (lang !== 'chinese') {
      list.push(
        language({
          id: `ap-${lang}-language`,
          name: `AP ${label} Language and Culture`,
          description: `College-level language and culture: interpersonal, interpretive, and presentational communication.`,
          level: 'ap',
          length: 'year',
          grades: g(11, 12),
          prerequisites: [before(`honors-${lang}-4`)],
          workload: 3,
          tags,
          sequence: { id: lang, step: 5 },
        }),
      )
    }
    return list
  }),

  // Health and physical education
  course({
    id: 'health',
    name: 'Health',
    department: 'health-pe',
    description: 'Nutrition, mental health, substance-use prevention, relationships, and first aid.',
    length: 'semester',
    grades: ALL,
    workload: 1,
    tags: ['health', 'wellness'],
    satisfies: ['health'],
  }),
  course({
    id: 'physical-education',
    name: 'Physical Education',
    department: 'health-pe',
    description: 'Fitness, team and individual sports, and lifelong wellness habits.',
    length: 'year',
    grades: g(9, 10),
    workload: 1,
    tags: ['fitness'],
    satisfies: ['pe'],
  }),
  course({
    id: 'strength-conditioning',
    name: 'Strength and Conditioning',
    department: 'health-pe',
    description: 'Weight training, speed, and conditioning programs, with an emphasis on safe technique.',
    length: 'semester',
    grades: g(10, 11, 12),
    workload: 1,
    tags: ['fitness', 'athletics'],
  }),
  course({
    id: 'team-sports',
    name: 'Team Sports',
    department: 'health-pe',
    description: 'Strategy and skills across seasonal team sports.',
    length: 'semester',
    grades: g(10, 11, 12),
    workload: 1,
    tags: ['fitness', 'athletics'],
  }),

  // Fine arts
  arts({
    id: 'art-1',
    name: 'Art 1: Foundations',
    description: 'Drawing, color, and design fundamentals across a range of media.',
    length: 'year',
    grades: ALL,
    tags: ['arts', 'design'],
  }),
  arts({
    id: 'drawing-painting',
    name: 'Drawing and Painting',
    description: 'Observational drawing and painting in acrylic and watercolor, building toward a portfolio.',
    length: 'year',
    grades: g(10, 11, 12),
    prerequisites: [before('art-1')],
    tags: ['arts', 'design'],
  }),
  arts({
    id: 'ceramics',
    name: 'Ceramics',
    description: 'Hand-building and wheel-throwing, glazing, and firing.',
    length: 'semester',
    grades: ALL,
    workload: 1,
    tags: ['arts', 'design'],
  }),
  arts({
    id: 'digital-photography',
    name: 'Digital Photography',
    description: 'Camera controls, composition, lighting, and photo editing.',
    length: 'semester',
    grades: g(10, 11, 12),
    tags: ['arts', 'media', 'design'],
  }),
  arts({
    id: 'graphic-design',
    name: 'Graphic Design',
    description: 'Typography, layout, and branding using industry design software.',
    length: 'semester',
    grades: g(10, 11, 12),
    tags: ['arts', 'design', 'media'],
  }),
  arts({
    id: 'ap-art-design',
    name: 'AP 2-D Art and Design',
    description: 'A year-long, self-directed portfolio investigation submitted for AP scoring.',
    level: 'ap',
    length: 'year',
    grades: g(11, 12),
    prerequisites: [before('drawing-painting')],
    workload: 3,
    tags: ['arts', 'design'],
  }),
  arts({
    id: 'concert-band',
    name: 'Concert Band',
    description: 'Wind and percussion ensemble with seasonal concerts. Can be repeated each year.',
    length: 'year',
    grades: ALL,
    tags: ['arts', 'music', 'performing-arts'],
    maxEnrollments: 4,
    expectsBackground: true,
    notes: ['Students should already play a band instrument.'],
  }),
  arts({
    id: 'concert-choir',
    name: 'Concert Choir',
    description: 'Vocal ensemble singing a range of styles, with seasonal concerts. Can be repeated each year.',
    length: 'year',
    grades: ALL,
    tags: ['arts', 'music', 'performing-arts'],
    maxEnrollments: 4,
  }),
  arts({
    id: 'theater-arts',
    name: 'Theater Arts',
    description: 'Acting, improvisation, and stagecraft, ending in a public performance.',
    length: 'year',
    grades: ALL,
    tags: ['arts', 'performing-arts', 'public-speaking'],
  }),
  arts({
    id: 'ap-music-theory',
    name: 'AP Music Theory',
    description: 'Harmony, ear training, sight-singing, and composition at a college-introductory level.',
    level: 'ap',
    length: 'year',
    grades: g(10, 11, 12),
    workload: 3,
    tags: ['arts', 'music'],
    expectsBackground: true,
    notes: ['Prior music study is recommended.'],
  }),

  // Computer science
  course({
    id: 'intro-computer-science',
    name: 'Introduction to Computer Science',
    department: 'computer-science',
    description: 'Programming fundamentals in Python: variables, loops, functions, and small projects.',
    length: 'semester',
    grades: ALL,
    tags: ['computer-science', 'engineering'],
  }),
  course({
    id: 'ap-computer-science-principles',
    name: 'AP Computer Science Principles',
    department: 'computer-science',
    description: 'The big ideas of computing: data, the internet, algorithms, and the impact of technology, with a programming project.',
    level: 'ap',
    length: 'year',
    grades: ALL,
    tags: ['computer-science'],
  }),
  course({
    id: 'ap-computer-science-a',
    name: 'AP Computer Science A',
    department: 'computer-science',
    description: 'Object-oriented programming in Java, equivalent to a first college programming course.',
    level: 'ap',
    length: 'year',
    grades: g(10, 11, 12),
    prerequisites: [before(...ALGEBRA_1)],
    workload: 3,
    tags: ['computer-science', 'engineering', 'math'],
  }),
  course({
    id: 'data-structures',
    name: 'Data Structures and Algorithms',
    department: 'computer-science',
    description: 'Lists, trees, graphs, and hash tables, and how to reason about an algorithm’s speed.',
    level: 'post-ap',
    length: 'semester',
    seasons: ['fall'],
    grades: g(11, 12),
    prerequisites: [before('ap-computer-science-a')],
    workload: 4,
    tags: ['computer-science', 'math'],
  }),
  course({
    id: 'web-development',
    name: 'Web Development',
    department: 'computer-science',
    description: 'Building websites with HTML, CSS, and JavaScript.',
    length: 'semester',
    grades: g(10, 11, 12),
    prerequisites: [before('intro-computer-science', 'ap-computer-science-principles', 'ap-computer-science-a')],
    tags: ['computer-science', 'design'],
  }),
  course({
    id: 'cybersecurity',
    name: 'Cybersecurity',
    department: 'computer-science',
    description: 'How systems are attacked and defended: networks, encryption, and ethical hacking.',
    length: 'semester',
    seasons: ['spring'],
    grades: g(10, 11, 12),
    prerequisites: [before('intro-computer-science', 'ap-computer-science-principles')],
    tags: ['computer-science'],
  }),

  // Engineering
  course({
    id: 'intro-engineering-design',
    name: 'Introduction to Engineering Design',
    department: 'engineering',
    description: 'The engineering design process, sketching, and 3D modeling, through hands-on projects.',
    length: 'year',
    grades: ALL,
    tags: ['engineering', 'design'],
  }),
  course({
    id: 'principles-of-engineering',
    name: 'Principles of Engineering',
    department: 'engineering',
    description: 'Mechanisms, energy, statics, and materials, applied in team build projects.',
    length: 'year',
    grades: g(10, 11, 12),
    prerequisites: [before('intro-engineering-design')],
    workload: 3,
    tags: ['engineering', 'physics'],
  }),
  course({
    id: 'robotics',
    name: 'Robotics',
    department: 'engineering',
    description: 'Design, build, and program robots for competition-style challenges.',
    length: 'semester',
    grades: g(10, 11, 12),
    prerequisites: [before('intro-engineering-design', 'intro-computer-science')],
    lab: true,
    tags: ['engineering', 'computer-science'],
  }),
  course({
    id: 'engineering-design-development',
    name: 'Engineering Design and Development',
    department: 'engineering',
    description: 'Capstone: identify a real problem, then research, design, prototype, and test a solution.',
    level: 'honors',
    length: 'year',
    grades: g(12),
    prerequisites: [before('principles-of-engineering')],
    workload: 3,
    tags: ['engineering', 'design'],
  }),

  // Business
  course({
    id: 'intro-business',
    name: 'Introduction to Business',
    department: 'business',
    description: 'How businesses start, operate, and compete, from marketing to management.',
    length: 'semester',
    grades: ALL,
    tags: ['business'],
  }),
  course({
    id: 'personal-finance',
    name: 'Personal Finance',
    department: 'business',
    description: 'Budgeting, banking, credit, taxes, and investing basics.',
    length: 'semester',
    grades: g(10, 11, 12),
    workload: 1,
    tags: ['business', 'finance'],
  }),
  course({
    id: 'accounting',
    name: 'Accounting',
    department: 'business',
    description: 'Recording transactions, financial statements, and the accounting cycle.',
    length: 'year',
    grades: g(10, 11, 12),
    tags: ['business', 'finance'],
  }),
  course({
    id: 'marketing',
    name: 'Marketing',
    department: 'business',
    description: 'Market research, branding, advertising, and digital marketing campaigns.',
    length: 'semester',
    grades: g(10, 11, 12),
    tags: ['business', 'media'],
  }),
  course({
    id: 'entrepreneurship',
    name: 'Entrepreneurship',
    department: 'business',
    description: 'Develop a business idea into a plan and pitch it to a panel.',
    length: 'semester',
    seasons: ['spring'],
    grades: g(11, 12),
    prerequisites: [before('intro-business', 'marketing')],
    tags: ['business', 'leadership'],
  }),

  // Health science
  course({
    id: 'intro-health-sciences',
    name: 'Introduction to Health Sciences',
    department: 'health-science',
    description: 'Careers in healthcare, medical ethics, and basic clinical skills like vital signs and CPR.',
    length: 'year',
    grades: g(10, 11, 12),
    tags: ['medicine', 'health-science', 'biology'],
  }),
  course({
    id: 'medical-terminology',
    name: 'Medical Terminology',
    department: 'health-science',
    description: 'The language of medicine: roots, prefixes, and suffixes used across body systems.',
    length: 'semester',
    grades: g(10, 11, 12),
    workload: 1,
    tags: ['medicine', 'health-science'],
  }),
  course({
    id: 'sports-medicine',
    name: 'Sports Medicine',
    department: 'health-science',
    description: 'Preventing, assessing, and treating athletic injuries.',
    length: 'semester',
    grades: g(11, 12),
    prerequisites: [before(...BIOLOGY)],
    tags: ['medicine', 'health-science', 'fitness'],
  }),

  // Interdisciplinary
  course({
    id: 'ap-seminar',
    name: 'AP Seminar',
    department: 'interdisciplinary',
    description: 'Research, argument, and presentation skills through team and individual projects on real-world issues.',
    level: 'ap',
    length: 'year',
    grades: g(10, 11),
    workload: 3,
    tags: ['research', 'writing', 'humanities'],
  }),
  course({
    id: 'ap-research',
    name: 'AP Research',
    department: 'interdisciplinary',
    description: 'A year-long independent research project and paper on a question you choose.',
    level: 'ap',
    length: 'year',
    grades: g(11, 12),
    prerequisites: [before('ap-seminar')],
    workload: 3,
    tags: ['research', 'writing', 'humanities'],
  }),
  course({
    id: 'leadership',
    name: 'Leadership',
    department: 'interdisciplinary',
    description: 'Student government and event planning, with a focus on communication and teamwork.',
    length: 'semester',
    grades: g(10, 11, 12),
    workload: 1,
    tags: ['leadership'],
  }),
]

export const DEMO_SCHOOL: SchoolConfig = {
  id: 'compass-demo',
  name: 'Compass Demo High School',
  isDemo: true,
  load: { min: 6, max: 7 },
  totalCredits: 24,
  preHighSchoolCredit: false,
  departments: [
    { id: 'english', name: 'English', shortName: 'English', order: 0, lane: true },
    { id: 'math', name: 'Mathematics', shortName: 'math', order: 1, lane: true },
    { id: 'science', name: 'Science', order: 2, lane: true },
    { id: 'social-studies', name: 'Social Studies', order: 3, lane: true },
    { id: 'world-language', name: 'World Language', order: 4, lane: true },
    { id: 'health-pe', name: 'Health & PE', order: 5, lane: false },
    { id: 'fine-arts', name: 'Fine Arts', order: 6, lane: false },
    { id: 'computer-science', name: 'Computer Science', order: 7, lane: false },
    { id: 'engineering', name: 'Engineering', order: 8, lane: false },
    { id: 'business', name: 'Business', order: 9, lane: false },
    { id: 'health-science', name: 'Health Sciences', order: 10, lane: false },
    { id: 'interdisciplinary', name: 'Interdisciplinary', order: 11, lane: false },
  ],
  requirements: [
    { id: 'english', name: 'English', description: 'Four years of English.', credits: 4, kind: 'category', source: SEED },
    { id: 'math', name: 'Mathematics', description: 'Four credits of mathematics.', credits: 4, kind: 'category', source: SEED },
    {
      id: 'science',
      name: 'Science',
      description: 'Three credits of lab science, including Biology and a physical science.',
      credits: 3,
      kind: 'category',
      mustInclude: [
        { label: 'Biology', anyOf: BIOLOGY },
        { label: 'a physical science (Chemistry or Physics)', anyOf: [...CHEMISTRY, 'physics', 'ap-physics-1'] },
      ],
      source: SEED,
    },
    {
      id: 'social-studies',
      name: 'Social Studies',
      description: 'Three credits, including World History, U.S. History, U.S. Government, and Economics.',
      credits: 3,
      kind: 'category',
      mustInclude: [
        { label: 'World History', anyOf: ['world-history', 'honors-world-history', 'ap-world-history'] },
        { label: 'U.S. History', anyOf: ['us-history', 'ap-us-history'] },
        { label: 'U.S. Government', anyOf: ['us-government', 'ap-us-government'] },
        { label: 'Economics', anyOf: ['economics', 'ap-macroeconomics', 'ap-microeconomics'] },
      ],
      source: SEED,
    },
    {
      id: 'world-language',
      name: 'World Language',
      description: 'Two credits of the same world language.',
      credits: 2,
      kind: 'category',
      sameSequence: true,
      source: SEED,
    },
    {
      id: 'health',
      name: 'Health',
      description: 'One semester of Health.',
      credits: 0.5,
      kind: 'category',
      mustInclude: [{ label: 'Health', anyOf: ['health'] }],
      source: SEED,
    },
    { id: 'pe', name: 'Physical Education', description: 'One credit of physical education.', credits: 1, kind: 'category', source: SEED },
    { id: 'fine-arts', name: 'Fine Arts', description: 'One credit of visual or performing arts.', credits: 1, kind: 'category', source: SEED },
    {
      id: 'electives',
      name: 'Electives',
      description: 'Credits from any course beyond the other requirements.',
      credits: 5.5,
      kind: 'elective',
      source: SEED,
    },
  ],
  policies: [
    {
      kind: 'every-term',
      id: 'math-every-term',
      label: 'Your school’s default plan keeps math in every semester',
      department: 'math',
      enforcement: 'required',
      source: MODEL,
    },
    {
      kind: 'placement',
      id: 'world-history-freshman',
      label: 'Your school’s default sequence places World History in freshman year',
      courseIds: ['world-history', 'honors-world-history'],
      grade: 9,
      enforcement: 'target',
      source: MODEL,
    },
    {
      kind: 'placement',
      id: 'health-sophomore',
      label: 'Your school’s default sequence places Health in sophomore year',
      courseIds: ['health'],
      grade: 10,
      enforcement: 'target',
      source: MODEL,
    },
    {
      kind: 'sequence-continuity',
      id: 'language-continuity',
      label: 'World languages are taken in consecutive years',
      enforcement: 'target',
      source: MODEL,
    },
  ],
  courses,
  mathPlacement: [
    { id: 'pre-algebra', label: 'Pre-Algebra or Math 8', completes: [], description: 'You’ll start high school with Algebra 1.' },
    { id: 'algebra-1', label: 'Algebra 1', completes: ['algebra-1'] },
    { id: 'geometry', label: 'Geometry', completes: ['algebra-1', 'geometry'] },
    { id: 'honors-geometry', label: 'Honors Geometry', completes: ['algebra-1', 'honors-geometry'] },
    { id: 'algebra-2', label: 'Algebra 2', completes: ['algebra-1', 'geometry', 'algebra-2'] },
    { id: 'honors-algebra-2', label: 'Honors Algebra 2', completes: ['algebra-1', 'geometry', 'honors-algebra-2'] },
  ],
  source: SEED,
}
