import Link from 'next/link'
import { getViewer } from '@/lib/auth/viewer'
import { samplePlan } from '@/lib/sample'
import { RouteField } from '@/components/marketing/route-field'
import { SamplePlan } from '@/components/marketing/sample-plan'
import { Logo } from '@/components/ui/logo'
import { IconArrowRight, IconCheckCircle } from '@/components/ui/icons'

export default async function Home() {
  const viewer = await getViewer()
  const sample = samplePlan()
  const primaryHref = viewer ? (viewer.student.onboarded ? '/home' : '/onboarding') : '/sign-up'
  const primaryLabel = viewer ? (viewer.student.onboarded ? 'Open my plan' : 'Finish my plan') : 'Build My Plan'

  return (
    <div className="min-h-dvh">
      <header className="absolute inset-x-0 top-0 z-10 mx-auto flex max-w-[1240px] items-center justify-between px-5 py-5 md:px-8">
        <Link href="/" aria-label="Compass home">
          <Logo />
        </Link>
        <nav className="flex items-center gap-1.5" aria-label="Account">
          {viewer ? null : (
            <Link href="/sign-in" className="btn btn-quiet btn-sm">
              Sign in
            </Link>
          )}
          <Link href={primaryHref} className="btn btn-primary btn-sm">
            {primaryLabel}
          </Link>
        </nav>
      </header>

      <main>
        <section className="relative isolate overflow-hidden">
          <RouteField />
          <div className="relative mx-auto max-w-[1240px] px-5 pb-24 pt-36 md:px-8 md:pb-32 md:pt-44">
            <div className="max-w-[640px] animate-rise">
              <h1 className="text-[44px] font-semibold leading-[1.02] tracking-[-0.035em] md:text-[68px]">
                Your four years.
                <br />
                <span className="text-mist">Mapped.</span>
              </h1>
              <p className="mt-6 max-w-[520px] text-[17px] leading-relaxed text-mist md:text-[19px]">
                Compass turns graduation requirements, prerequisites, and your goals into a personalized path through
                high school.
              </p>
              <div className="mt-9 flex flex-wrap items-center gap-3">
                <Link href={primaryHref} className="btn btn-primary h-11 px-5 text-[15px]">
                  {primaryLabel}
                  <IconArrowRight />
                </Link>
                <a href="#how" className="btn btn-ghost h-11 px-5 text-[15px]">
                  Explore Compass
                </a>
              </div>
            </div>
          </div>
        </section>

        <section aria-labelledby="preview-title" className="mx-auto max-w-[1240px] px-5 md:px-8">
          <div className="flex flex-wrap items-end justify-between gap-4">
            <div>
              <p className="eyebrow">A real plan</p>
              <h2 id="preview-title" className="mt-2 text-2xl font-semibold md:text-3xl">
                Every course, in context.
              </h2>
              <p className="mt-2 max-w-[620px] text-mist">
                A sample student who finished Algebra 1 in eighth grade, wants engineering, and asked for a very
                rigorous schedule. This plan was generated by the Compass engine against the demo catalog. Select any
                course to see what leads to it and what it opens.
              </p>
            </div>
            <p className="flex items-center gap-2 text-sm text-mist">
              <IconCheckCircle className="text-ok" /> Graduation path: {sample.status === 'valid' ? 'Valid' : 'Needs attention'}
            </p>
          </div>
          <div className="surface mt-6 p-3 md:p-5">
            <SamplePlan school={sample.school} placements={sample.placements} focusKey={sample.focusKey} />
          </div>
          <div className="mt-4 grid gap-4 md:grid-cols-2">
            <figure className="surface p-5">
              <figcaption className="eyebrow">Why is {sample.explanation.course} there?</figcaption>
              <p className="mt-3 text-[15px] leading-relaxed text-ink">{sample.explanation.headline}</p>
              <ul className="mt-3 space-y-1.5 text-sm text-mist">
                {sample.explanation.facts.map((f) => (
                  <li key={f} className="flex gap-2">
                    <span className="mt-2 h-1 w-1 shrink-0 rounded-full bg-fog" />
                    {f}
                  </li>
                ))}
              </ul>
            </figure>
            <figure className="surface p-5">
              <figcaption className="eyebrow">Why can’t a junior with only Algebra 1 take Multivariable Calculus?</figcaption>
              <p className="mt-3 text-[15px] leading-relaxed text-ink">{sample.blocked}</p>
              <p className="mt-3 text-sm text-fog">Answered by walking the prerequisite graph, not by guessing.</p>
            </figure>
          </div>
        </section>

        <section id="how" aria-labelledby="how-title" className="mx-auto mt-28 max-w-[1240px] scroll-mt-10 px-5 md:px-8">
          <p className="eyebrow">How it works</p>
          <h2 id="how-title" className="mt-2 max-w-[720px] text-2xl font-semibold md:text-3xl">
            Where you are. Where you can go. What gets you there.
          </h2>
          <ol className="mt-10 grid gap-px overflow-hidden rounded-2xl border border-line bg-line md:grid-cols-3">
            {[
              {
                n: '01',
                title: 'Where you are',
                body: 'Your grade, the math you finished before high school, and the courses already behind you. Compass never restarts a sequence you’ve completed.',
              },
              {
                n: '02',
                title: 'Where you can go',
                body: 'Every course is a node in a prerequisite graph. Compass knows what each one needs, when it’s offered, and whether it still fits before graduation.',
              },
              {
                n: '03',
                title: 'What gets you there',
                body: 'A complete four-year plan: six to seven courses a semester, every requirement met, every prerequisite in order — checked before you ever see it.',
              },
            ].map((step) => (
              <li key={step.n} className="bg-carbon p-6 md:p-8">
                <span className="font-mono text-xs text-signal">{step.n}</span>
                <h3 className="mt-4 text-lg font-medium">{step.title}</h3>
                <p className="mt-2 text-[15px] leading-relaxed text-mist">{step.body}</p>
              </li>
            ))}
          </ol>
        </section>

        <section aria-labelledby="engine-title" className="mx-auto mt-28 max-w-[1240px] px-5 md:px-8">
          <div className="grid gap-10 md:grid-cols-[1fr_1.1fr] md:gap-16">
            <div>
              <p className="eyebrow">The principle</p>
              <h2 id="engine-title" className="mt-2 text-2xl font-semibold md:text-3xl">
                AI explains the path.
                <br />
                <span className="text-mist">The engine proves it.</span>
              </h2>
              <p className="mt-4 text-[15px] leading-relaxed text-mist">
                Compass AI can talk through your goals and explain your plan. But it never decides what’s allowed.
                Prerequisites, availability, grade limits, and graduation requirements come from your school’s course
                data and are checked by a deterministic engine — the same answer every time.
              </p>
            </div>
            <div className="surface divide-y divide-line">
              {[
                ['Prerequisites', 'Every course’s prerequisites are completed or scheduled first.'],
                ['Availability', 'Every course is offered in its semester and open to your grade.'],
                ['Requirements', 'Every graduation requirement is covered, credit by credit.'],
                ['Reachability', 'Every course you want still fits in the semesters you have left.'],
              ].map(([title, body]) => (
                <div key={title} className="flex items-start gap-3 p-5">
                  <IconCheckCircle className="mt-0.5 text-ok" />
                  <div>
                    <p className="font-medium">{title}</p>
                    <p className="mt-0.5 text-sm text-mist">{body}</p>
                  </div>
                </div>
              ))}
            </div>
          </div>
        </section>

        {sample.scenario ? (
          <section aria-labelledby="whatif-title" className="mx-auto mt-28 max-w-[1240px] px-5 md:px-8">
            <p className="eyebrow">What if?</p>
            <h2 id="whatif-title" className="mt-2 text-2xl font-semibold md:text-3xl">
              See what changes before you change it.
            </h2>
            <p className="mt-2 max-w-[640px] text-mist">
              The sample student asks: what if I take AP Chemistry instead of AP Physics 2? Compass re-plans and shows
              the consequences. It doesn’t tell you which route is better — that’s your call.
            </p>
            <div className="surface mt-6 grid gap-6 p-5 md:grid-cols-3 md:p-6">
              <div>
                <p className="eyebrow">Scenario</p>
                <p className="mt-2 font-medium">{sample.scenario.title}</p>
                <p className="mt-2 flex items-center gap-2 text-sm text-mist">
                  <IconCheckCircle className="text-ok" /> {sample.scenario.status === 'valid' ? 'Still a valid path' : 'No valid path'}
                </p>
              </div>
              <div>
                <p className="eyebrow">What moves</p>
                <ul className="mt-2 space-y-1.5 text-sm text-mist">
                  {[...sample.scenario.downstream, ...sample.scenario.prerequisites].slice(0, 5).map((t) => (
                    <li key={t}>{t}</li>
                  ))}
                  {sample.scenario.downstream.length + sample.scenario.prerequisites.length === 0 ? <li>Nothing else moves.</li> : null}
                </ul>
              </div>
              <div>
                <p className="eyebrow">Requirements</p>
                <ul className="mt-2 space-y-1.5 text-sm text-mist">
                  {sample.scenario.requirements.length ? sample.scenario.requirements.map((t) => <li key={t}>{t}</li>) : <li>Every requirement is still covered.</li>}
                </ul>
              </div>
            </div>
          </section>
        ) : null}

        <section className="mx-auto mt-28 max-w-[1240px] px-5 pb-24 md:px-8">
          <div className="surface flex flex-col items-start justify-between gap-6 p-8 md:flex-row md:items-center md:p-10">
            <div>
              <h2 className="text-2xl font-semibold">Start from where you are.</h2>
              <p className="mt-2 text-mist">About five minutes. Your plan is private to you.</p>
            </div>
            <Link href={primaryHref} className="btn btn-primary h-11 px-5 text-[15px]">
              {primaryLabel}
              <IconArrowRight />
            </Link>
          </div>
        </section>
      </main>

      <footer className="border-t border-line">
        <div className="mx-auto flex max-w-[1240px] flex-col gap-2 px-5 py-8 text-sm text-fog md:flex-row md:justify-between md:px-8">
          <span>Compass</span>
          <span>The demo catalog is fictional development data, not a real school’s requirements.</span>
        </div>
      </footer>
    </div>
  )
}
